# docker run -d --name=grafana -p 3000:3000 grafana/grafana-enterprise

services:
  grafana:
    # image: grafana/grafana-enterprise
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway