# run only cadvisor

services:
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    command:
      # - '--config.file=/etc/prometheus/prometheus.yml'
      - ${CADVISOR_CMD}
    ports: 
      - 8081:8080
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    # assuming any redis at host is ran
    # depends_on:
    #   - redis-mon
    
  # redis-mon: 
  #   image: redis:latest
  #   container_name: redis-mon
  #   ports: 
  #     - 6379:6379