# docker run -d --name=grafana -p 3000:3000 grafana/grafana-enterprise

services:
  grafana:
    # image: grafana/grafana-enterprise
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      # persist prom
      - ./var/prometheus:/prometheus
      # - ./etc/prometheus/docker-prometheus.yml:/etc/prometheus/prometheus.yml
      - ${MOUNT_PROM_YML}:/etc/prometheus/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - node_exporter

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    ports: 
      - 8081:8080
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    
    # assuming any redis at host is ran
    # depends_on:
    #   - redis-mon
    
  # redis-mon: 
  #   image: redis:latest
  #   container_name: redis-mon
  #   ports: 
  #     - 6379:6379